Deterministic route url
konveyor/pvc-migrate pull request #124
Opened 2020-08-07 01:31 UTC by alaypatel07

2020-08-07 01:51 UTC, alaypatel07 commented
I kindda felt guilty on not safeguarding us against @pranavgaikwad's and @eriknelson's concern. This should take us through url problems and fix #121 for good

2020-08-07 01:52 UTC, alaypatel07 commented
thanks @pranavgaikwad for finding this condition https://github.com/konveyor/pvc-migrate/pull/124/files#diff-ec761466459b9bccb474c7eb8cba7b17R133, great stuff digging this!

2020-08-07 17:01 UTC, pranavgaikwad requested changes
Overall good. Nested clauses can be converted to `dict.get()` format

2020-08-07 17:01 UTC, pranavgaikwad commented on 3_run_rsync/tasks/create-pod-service.yml
> +        and ingress_controller.resources.status is defined
Overall, looks good. Just one improvement: you can replace the nested `and` clauses into `ingress_controller.get('resources', {}).get('status', {}).get('domain', '') != ''` 

Also, a typo: `if defined` should be `is defined`

2020-08-07 19:01 UTC, alaypatel07 commented on 3_run_rsync/tasks/create-pod-service.yml
> +        and ingress_controller.resources.status is defined
+1. replaced

2020-08-10 14:19 UTC, pranavgaikwad requested changes

2020-08-10 14:19 UTC, pranavgaikwad commented on 3_run_rsync/tasks/create-pod-service.yml
> +          and rsync_route.resources[0].spec.host is defined
Same `dict.get()` here too. Either that, or all `and` keywords can be removed and conditions can be added as a list:
```yml
until:
- rsync_route.resources | length > 0
- rsync_route.resources[0].spec is defined
.
.
```
Ansible, by default, aggregates all conditions in the list with an `and` clause  between them.

Additionally, `resources` array is always defined in `k8s_facts` response. It's just empty when a resource of interest is not found. Therefore, `rsync_route.resources is defined` should really be `rsync_route.resources | length > 0`

2020-08-13 13:14 UTC, pranavgaikwad approved these changes
ACK

2020-08-13 13:41 UTC, merged