refactor all templates to have variables in double quotes
konveyor/pvc-migrate pull request #126
Opened 2020-08-19 21:13 UTC by alaypatel07

attempts to fix #125, pending testing

2020-08-19 21:14 UTC, alaypatel07 commented on 3_run_rsync/templates/pod.yml.j2
> +      - "echo "{{ mig_dest_ssh_user }}":$(echo $rsyncd_pass | base64 -d) > /etc/rsyncd.secrets && chmod 0600 /etc/rsyncd.secrets && /usr/bin/rsync --daemon --no-detach --port "{{ rsyncd_port }}" -vvv
this needs to be fixed

2020-08-20 13:43 UTC, pranavgaikwad requested changes
Overall, good. Question about one change in the `rsyncd` j2 template

2020-08-20 13:43 UTC, pranavgaikwad commented on 3_run_rsync/templates/rsyncd.yml.j2
> +        path = /mnt/"{ pvc_namespace }}"/"{ pvc.pvc_vol_safe_name }}"
Full quotes here: `"/mnt/{ pvc_namespace }}/{ pvc.pvc_vol_safe_name }}"`?

2020-08-21 14:36 UTC, pranavgaikwad approved these changes
ACK

2020-08-21 17:49 UTC, merged